ARG BASE_IMAGE=node:13.12.0-alpine3.11

FROM ${BASE_IMAGE}

MAINTAINER Aaron Rueth <arueth@mirantis.com>

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY package.json ./
RUN npm install

COPY src /home/node/app/src

EXPOSE 8080

CMD ["npm", "run", "dev-container"]
