apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pacman
  name: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pacman
  template:
    metadata:
      labels:
        name: pacman
    spec:
  #    affinity:
   #     nodeAffinity:
     #     requiredDuringSchedulingIgnoredDuringExecution:
        #    nodeSelectorTerms:
         #     - matchExpressions:
        #          - key: beta.kubernetes.io/os
           #         operator: In
           #         values:
           #           - linux
      containers:
        - image: pacman
          name: pacman
          ports:
            - containerPort: 8080
              name: http-server
